name: build-test-deploy
on: push
jobs: 
  build: #executes the build process on commit push
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3 #(checkout action, to access the code in our repo)
      - run: echo "$(cat hello_world.txt)" # now we'll setup a CI/CD Workflow
      - name: use node.js 
        uses: actions/setup-node@v3 #setup node action(since we're using nodejs)
        with:
          node-version: '18.x'
      - run: npm install
      - run: npm run build 
      #NOTE THAT JOBS ARE COMPLETELY INDEPENDENT OF EACH OTHER BY DEFAULT, STEPS ARE LOCAL SCOPED TO EACH JOB
  test: #Execs the test(only after build)
     #pre-requisite job for test, would only run if build job execution is successful(SINCE JOBS ARE INDEPENDENT WE NEED THIS)
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repo
        uses: actions/checkout@v3
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm install
      - run: npm test
  deploy: #build -> test -> deploy(final job)
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write     
      id-token: write
    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: checkout repo #STEP1
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: use node.js #STEP2
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          
      - name: configure github pages #STEP3 TO CONFIGURE GITHUB PAGES FOR OUR APP DEPLOYMENT
        uses: actions/configure-pages@v3
        with:
          static_site_generator: next
          
      - run: npm install
      - run: npm run build 

      - name: upload artifacts #STEP4(uploading the final static page build(inside ./out directory for nextjs app) to github pages
        uses: actions/upload-pages-artifact@v1
        with: 
          path: "./out"
          
      - name: deploy #STEP5(FINALLY DEPLOY)
        id: deployment
        uses: actions/deploy-pages@v1
